### ISSUE TITLE
Please add authentication and create user usage example 

### ISSUE THREAD

**Issue by mkvaghani** [thePanz/MattermostClient#6]
@thePanz   Please add authentication and create user usage example. 
Just wonder if we can use API for login similar to oauth2.0 authentication method. 
Thank you

**Comment by thePanz** [comment]
@mkvaghani the authentication is shown in the first example. This client uses the regular APIs, no OAuth2 authentication is provided here.

The user creation follows the same example for the Teams. 
API Call: https://github.com/thePanz/MattermostClient/blob/master/src/Api/UsersApi.php#L223
UserCreation parameters: use the UserBuilder class https://github.com/thePanz/MattermostClient/blob/master/src/Model/User/UserBuilder.php

**Comment by mkvaghani** [comment]
@thePanz  
Thank for quick reply. 

In first example we call http://localhost:8065/api/v4 this verify the user credential.

While authentication needs http://localhost:8065/api/v4/user/login and redirect to mattermost dashboard if credentials are success.

And example to create user:
```
<?php
namespace Pnz\MattermostClient;

require_once 'vendor/autoload.php';
require_once 'src/ApiClient.php';
require_once 'src/HttpClientConfigurator.php';

$endpoint = 'http://localhost:8065/api/v4';
$username = 'mkvaghani';
$password = 'mkvaghani';

$configurator = (new HttpClientConfigurator())
    ->setEndpoint($endpoint)
    ->setCredentials($username, $password);
$apiClient =  ApiClient::configure($configurator);

$result = $apiClient->users()->createUser([
    'email'    => 'test@test.com', 
    'username' => 'test', 
    'password' => 'testpsw'
]); //If result success. check the user below

//Get a user by username
$userbyname = $apiClient->users()->getUserByUsername('username'); 
$userbyid = $apiClient->users()->getUserById('me');
print_r($userbyname);

```

**Comment by thePanz** [comment]
The authentication is performed automatically when first invoking your API endpoint.

The right example would be:
```php
$endpoint = 'http://localhost:8065/api/v4';
$username = 'mkvaghani';
$password = 'mkvaghani';

$configurator = (new HttpClientConfigurator())
    ->setEndpoint($endpoint)
    ->setCredentials($username, $password);
$apiClient =  ApiClient::configure($configurator);

$userBuilder = (new UserBuilder())
  ->setEmail('test@test.com')
  ->setUsername('username')
  ->setPassword('password');

$user = $apiClient->users()->createUser($userBuilder->build())); 

print_r($user);
```

**Comment by mkvaghani** [comment]
@thePanz  Thank you. This is the right way to create user !

**Comment by thePanz** [comment]
Would you like open a PR to update the documentation?

**Comment by mkvaghani** [comment]
Well, it's not needed. 
But It would be great if you add **create user usage example** in readme file.
