### ISSUE TITLE
ChannelsApi::addChannelMember() parameters

### ISSUE THREAD

**Issue by Cyrille37** [thePanz/MattermostClient#7]
Hello,
Thanks a lot for your great work.

I do not understand why ChannelsApi::addChannelMember() does not match parameters of MM API [Add user to channel](https://api.mattermost.com/v4/#tag/channels%2Fpaths%2F~1channels~1%7Bchannel_id%7D~1members%2Fpost)

- Your method has `$roles` parameter but the MM API has not.
- The MM API has `post_root_id` parameter but not your method.

Thanks & cheers.

**Comment by thePanz** [comment]
Hi @Cyrille37 , good question! I guess that the API was changed, without a changelog from MM.
The method's parameters should be updated

**Comment by thePanz** [comment]
Fixed in 40de52c
