### ISSUE TITLE
error when composer require pnz/mattermost-client

### ISSUE THREAD

**Issue by burasuk** [thePanz/MattermostClient#8]
![image](https://user-images.githubusercontent.com/7629077/83001875-9d758d80-a00c-11ea-8c1a-7186518c3825.png)

**Comment by thePanz** [comment]
What's your output of `composer show`?

**Comment by burasuk** [comment]
`composer show`:

```sh
gnello/php-mattermost-driver v2.12.0 The Php Driver to interact with the Mattermost Web Service API
guzzlehttp/guzzle            6.5.4   Guzzle is a PHP HTTP client library
guzzlehttp/promises          v1.3.1  Guzzle promises library
guzzlehttp/psr7              1.6.1   PSR-7 message implementation that also provides common utility methods
pimple/pimple                v3.3.0  Pimple, a simple Dependency Injection Container
psr/container                1.0.0   Common Container Interface (PHP FIG PSR-11)
psr/http-message             1.0.1   Common interface for HTTP messages
ralouphie/getallheaders      3.0.3   A polyfill for getallheaders.
symfony/polyfill-intl-idn    v1.17.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring    v1.17.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.17.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
```
run on PHP 7.4

**Comment by thePanz** [comment]
From your first message `php-http/httplug` is already installed, but not listed from your second message.

Did you copy-n-paste all the installed packages?

btw: 
- if you're running php7.4, `symfony/polyfill-php72` is not needed

**Comment by burasuk** [comment]
Yes, i copy/paste command from readme.

In an empty folder i run:

`composer require php-http/curl-client nyholm/psr7 php-http/message pnz/mattermost-client`

and then i get above message.

**Comment by burasuk** [comment]
i see on master 

![image](https://user-images.githubusercontent.com/7629077/83266393-11599680-a1c3-11ea-92d5-170a2ac96047.png)

but on version 0.1.0 witch is download by composer it has:

![image](https://user-images.githubusercontent.com/7629077/83266508-33ebaf80-a1c3-11ea-8d14-8bb63f367a47.png)

on my machine wants version 2

![image](https://user-images.githubusercontent.com/7629077/83266722-8200b300-a1c3-11ea-992b-6dccbbefc4a6.png)

witch is correct when i look in https://github.com/php-http/curl-client/blob/master/composer.json

**Comment by Bharat-B** [comment]
Any update on this issue @thePanz

**Comment by peteratnsight** [comment]
@thePanz - do you have any news on this issue? I have just installed your package via composer as well as manually - though the composer.json refers to a HTTPlug 2.0 - the composer install is looking for a HTTPlug v1.0 As I cannot not downgrade the HTTPlug I am very much looking forward to a solution to this issue.

**Comment by rjbrown99** [comment]
It's fixed in the master branch - 

composer config minimum-stability dev
composer require --dev pnz/mattermost-client:master

That should "fix" it, the maintainers should really roll a new release from the master branch.

**Comment by thePanz** [comment]
Thanks for the update @peteratnsight and @rjbrown99 

The "master" branch is still in progress, I might tag a BETA releases soon tho
